# Generated by Django 4.2.10 on 2024-02-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('avg_rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
